spring:
  application:
    name: legou-store
  datasource:
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 10
      filters: stat,wall
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
        allow:
        deny:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
server:
  port: 8089


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
# 门店库
master:
  datasource:
    url: jdbc:mysql://localhost:3306/prd_store?characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=cou