server:
  port: 8090

spring:
  application:
    name: legou-service-registry
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
